spring.application.name=Redis
spring.data.mongodb.uri=mongodb+srv://njha5901:1234@cluster0.9kctgnp.mongodb.net/redis?retryWrites=true&w=majority&appName=Cluster0
spring.data.redis.host=cup-silent-hospitable-19979.db.redis.io
spring.data.redis.port=13402
spring.data.redis.username=default
spring.data.redis.password=lLQesspgCTqNzoxpB0SKU33uLs781hXC
spring.data.redis.ssl.enabled=false
server.port=8080